const languages: Record<string, Record<string, string>> = {
  en: {
    card_title: 'Battery Notes',
    col_name: 'Device',
    col_battery: 'Battery',
    col_type: 'Type',
    col_last_replaced: 'Last Replaced',
    col_status: 'Status',
    col_note: 'Note',
    col_actions: 'Actions',
    status_low: 'Low',
    status_ok: 'OK',
    status_critical: 'Critical',
    status_unavailable: 'Unavailable',
    action_mark_replaced: 'Mark replaced',
    action_replaced: 'Replaced',
    confirm_replace_title: 'Confirm Battery Replacement',
    confirm_replace_msg: 'Mark battery as replaced for "{name}"?',
    replaced_success: 'Battery replacement recorded',
    search_placeholder: 'Search devices, battery type...',
    filter_all: 'All',
    filter_low: 'Low',
    filter_critical: 'Critical',
    summary_total: 'Total',
    summary_low: 'Low',
    summary_ok: 'Good',
    no_devices: 'No Battery Notes devices found.',
    no_results: 'No matching devices found.',
    time_never: 'Never',
    time_today: 'Today',
    time_yesterday: 'Yesterday',
    time_days_ago: '{n}d ago',
    time_weeks_ago: '{n}w ago',
    time_months_ago: '{n}m ago',
    time_years_ago: '{n}y ago',
    editor_title: 'Title',
    editor_icon: 'Icon',
    editor_show_header: 'Show Header',
    editor_show_summary: 'Show Summary Counters',
    editor_show_search: 'Show Search Bar',
    editor_show_filters: 'Show Quick Filter Pills',
    editor_compact: 'Compact Layout',
    editor_confirm_replace: 'Confirm Before Replacement',
    editor_sort_by: 'Sort By',
    editor_sort_direction: 'Sort Direction',
    editor_filter_low_only: 'Show Low Battery Only',
    editor_filter_threshold: 'Battery Threshold (%)',
    editor_hide_unavailable: 'Hide Unavailable Devices',
    editor_columns: 'Visible Columns',
    editor_col_name: 'Name',
    editor_col_battery: 'Battery Level',
    editor_col_type: 'Battery Type',
    editor_col_last_replaced: 'Last Replaced',
    editor_col_status: 'Status Badge',
    editor_col_note: 'Note',
    editor_col_actions: 'Action Button',
  },
  de: {
    card_title: 'Batteriestände',
    col_name: 'Gerät',
    col_battery: 'Batterie',
    col_type: 'Typ',
    col_last_replaced: 'Zuletzt gewechselt',
    col_status: 'Status',
    col_note: 'Notiz',
    col_actions: 'Aktionen',
    status_low: 'Niedrig',
    status_ok: 'OK',
    status_critical: 'Kritisch',
    status_unavailable: 'Nicht verfügbar',
    action_mark_replaced: 'Als gewechselt markieren',
    action_replaced: 'Gewechselt',
    confirm_replace_title: 'Batteriewechsel bestätigen',
    confirm_replace_msg: 'Batterie für "{name}" wirklich als gewechselt markieren?',
    replaced_success: 'Batteriewechsel gespeichert',
    search_placeholder: 'Gerät oder Batterietyp suchen...',
    filter_all: 'Alle',
    filter_low: 'Niedrig',
    filter_critical: 'Kritisch',
    summary_total: 'Gesamt',
    summary_low: 'Niedrig',
    summary_ok: 'In Ordnung',
    no_devices: 'Keine Battery Notes Geräte gefunden.',
    no_results: 'Keine passenden Geräte gefunden.',
    time_never: 'Nie',
    time_today: 'Heute',
    time_yesterday: 'Gestern',
    time_days_ago: 'Vor {n} Tagen',
    time_weeks_ago: 'Vor {n} Wochen',
    time_months_ago: 'Vor {n} Monaten',
    time_years_ago: 'Vor {n} Jahren',
    editor_title: 'Titel',
    editor_icon: 'Icon',
    editor_show_header: 'Kopfzeile anzeigen',
    editor_show_summary: 'Zusammenfassung (Zähler) anzeigen',
    editor_show_search: 'Suchleiste anzeigen',
    editor_show_filters: 'Filter-Buttons anzeigen',
    editor_compact: 'Kompakte Tabelle',
    editor_confirm_replace: 'Bestätigungsdialog vor Wechsel',
    editor_sort_by: 'Sortieren nach',
    editor_sort_direction: 'Sortierrichtung',
    editor_filter_low_only: 'Nur schwache Batterien anzeigen',
    editor_filter_threshold: 'Schwellenwert (%)',
    editor_hide_unavailable: 'Nicht verfügbare ausblenden',
    editor_columns: 'Sichtbare Spalten',
    editor_col_name: 'Name',
    editor_col_battery: 'Batteriestand',
    editor_col_type: 'Batterietyp',
    editor_col_last_replaced: 'Zuletzt gewechselt',
    editor_col_status: 'Status',
    editor_col_note: 'Notiz',
    editor_col_actions: 'Aktions-Button',
  },
};

export function localize(stringKey: string, lang = 'en', replace?: Record<string, string | number>): string {
  const langKey = lang.startsWith('de') ? 'de' : 'en';
  let translated = languages[langKey]?.[stringKey] || languages['en']?.[stringKey] || stringKey;

  if (replace) {
    for (const [key, val] of Object.entries(replace)) {
      translated = translated.replace(new RegExp(`\\{${key}\\}`, 'g'), String(val));
    }
  }

  return translated;
}
